insert into MPA(NAME) values ('G' );
insert into MPA(NAME) values ('PG' );
insert into MPA(NAME) values ('PG-13' );
insert into MPA(NAME) values ( 'R' );
insert into MPA(NAME) values ( 'NC-17' );
insert into GENRES(NAME) values ('Комедия');
insert into GENRES(NAME) values ('Драма');
insert into GENRES(NAME) values ('Мультфильм');
insert into GENRES(NAME) values ('Триллер');
insert into GENRES(NAME) values ('Документальный');
insert into GENRES(NAME) values ('Боевик');